spring:
  cloud:
    gateway:
      routes:
        - id: spring6Training_5
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/*
        - id: Spring6ReactiveExperiments
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/*
        - id: Spring6ReactiveMongoExperiments
          uri: http://localhost:8083
          predicates:
            - Path=/api/v3/*
#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true
#
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: trace